In [1]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Read the input file and check the data dimension

In [2]:
cred = pd.read_csv('german_credit.csv')
cred.head()

default account_check_status  duration_in_month  \
0        0               < 0 DM                  6   
1        1    0 <= ... < 200 DM                 48   
2        0  no checking account                 12   
3        0               < 0 DM                 42   
4        1               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex  ... present_res_since  \
0                        male : single  ...                 4   
1  female : divorced/separated/married  ...                 2   
2                        male : single  ...                 3   
3                        male : single  ...                 4   
4                        male : single  ...                 4   

                                            property age  \
0                                        real estate  67   
1                                        real estate  22   
2                                        real estate  49   
3  if not A121 : building society savings agreeme...  45   
4                              unknown / no property  53   

   other_installment_plans   housing credits_this_bank  \
0                     none       own                 2   
1                     none       own                 1   
2                     none       own                 1   
3                     none  for free                 1   
4                     none  for free                 2   

                           job people_under_maintenance  \
0  skilled employee / official                        1   
1  skilled employee / official                        1   
2         unskilled - resident                        2   
3  skilled employee / official                        2   
4  skilled employee / official                        2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes  

[5 rows x 21 columns]

In [3]:
cred.shape

(1000, 21)

In [4]:
cred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
default                       1000 non-null int64
account_check_status          1000 non-null object
duration_in_month             1000 non-null int64
credit_history                1000 non-null object
purpose                       1000 non-null object
credit_amount                 1000 non-null int64
savings                       1000 non-null object
present_emp_since             1000 non-null object
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null object
other_debtors                 1000 non-null object
present_res_since             1000 non-null int64
property                      1000 non-null object
age                           1000 non-null int64
other_installment_plans       1000 non-null object
housing                       1000 non-null object
credits_this_bank             1000 non-null int64
job                           1000

In [5]:
# You can access from https://www.kaggle.com/uciml/german-credit
#Read input file and understand the data
# "default" is my dependent variable

### Q1 Randomly select 50% data for this use case( 1 Marks)
###### Hint: Use train_test_split

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
# Copy all the independent/predictor variables into X dataframe. Since 'default' is dependent variable drop it
X = cred.drop('default', axis=1)

# Copy the 'default' column alone into the y dataframe. This is the dependent variable
y = cred[['default']]

In [8]:
X.head()

account_check_status  duration_in_month  \
0               < 0 DM                  6   
1    0 <= ... < 200 DM                 48   
2  no checking account                 12   
3               < 0 DM                 42   
4               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex other_debtors  present_res_since  \
0                        male : single          none                  4   
1  female : divorced/separated/married          none                  2   
2                        male : single          none                  3   
3                        male : single     guarantor                  4   
4                        male : single          none                  4   

                                            property  age  \
0                                        real estate   67   
1                                        real estate   22   
2                                        real estate   49   
3  if not A121 : building society savings agreeme...   45   
4                              unknown / no property   53   

  other_installment_plans   housing  credits_this_bank  \
0                    none       own                  2   
1                    none       own                  1   
2                    none       own                  1   
3                    none  for free                  1   
4                    none  for free                  2   

                           job  people_under_maintenance  \
0  skilled employee / official                         1   
1  skilled employee / official                         1   
2         unskilled - resident                         2   
3  skilled employee / official                         2   
4  skilled employee / official                         2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes

In [9]:
y.head()

default
0        0
1        1
2        0
3        0
4        1

In [10]:
# Split X and y into training and test set in 50:50 ratio

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=1)

In [11]:
from sklearn.model_selection import train_test_split
train_data,test_data = train_test_split(cred,test_size=0.5,shuffle=True,stratify=cred['default'])
print(train_data.shape,test_data.shape)
y_train = train_data['default']
x_train = train_data.drop('default',inplace=False,axis=1)

(500, 21) (500, 21)


In [12]:
# Lets build a Ensemble model but need to modify the dataset first


### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [13]:
cred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
default                       1000 non-null int64
account_check_status          1000 non-null object
duration_in_month             1000 non-null int64
credit_history                1000 non-null object
purpose                       1000 non-null object
credit_amount                 1000 non-null int64
savings                       1000 non-null object
present_emp_since             1000 non-null object
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null object
other_debtors                 1000 non-null object
present_res_since             1000 non-null int64
property                      1000 non-null object
age                           1000 non-null int64
other_installment_plans       1000 non-null object
housing                       1000 non-null object
credits_this_bank             1000 non-null int64
job                           1000

In [14]:
cred.columns

Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')

In [15]:

# Print Shape of model data
x_train_data_tf=pd.get_dummies(x_train)
x_train_data_tf.shape

(500, 61)

In [16]:
# Print Shape of model data

### Check for highly correlated variables but don't required any treatment for this use case

In [17]:
x_train_data_tf.corr()

duration_in_month  \
duration_in_month                                            1.000000   
credit_amount                                                0.638527   
installment_as_income_perc                                   0.025076   
present_res_since                                            0.016256   
age                                                         -0.031522   
credits_this_bank                                           -0.004361   
people_under_maintenance                                    -0.034891   
account_check_status_0 <= ... < 200 DM                       0.107937   
account_check_status_< 0 DM                                  0.047080   
account_check_status_>= 200 DM / salary assignm...          -0.103864   
account_check_status_no checking account                    -0.088087   
credit_history_all credits at this bank paid ba...           0.009136   
credit_history_critical account/ other credits ...          -0.033772   
credit_history_delay in paying off in the past               0.158979   
credit_history_existing credits paid back duly ...          -0.095620   
credit_history_no credits taken/ all credits pa...           0.091564   
purpose_(vacation - does not exist?)                        -0.045233   
purpose_business                                             0.135095   
purpose_car (new)                                           -0.119112   
purpose_car (used)                                           0.136736   
purpose_domestic appliances                                 -0.061448   
purpose_education                                           -0.003482   
purpose_furniture/equipment                                  0.161720   
purpose_radio/television                                    -0.018056   
purpose_repairs                                             -0.003064   
purpose_retraining                                          -0.084288   
savings_.. >= 1000 DM                                       -0.059695   
savings_... < 100 DM                                        -0.028122   
savings_100 <= ... < 500 DM                                  0.050956   
savings_500 <= ... < 1000 DM                                -0.099840   
...                                                               ...   
present_emp_since_.. >= 7 years                              0.033504   
present_emp_since_... < 1 year                              -0.080051   
present_emp_since_1 <= ... < 4 years                        -0.004900   
present_emp_since_4 <= ... < 7 years                         0.048283   
present_emp_since_unemployed                                -0.004713   
personal_status_sex_female : divorced/separated...          -0.056376   
personal_status_sex_male : divorced/separated                0.003485   
personal_status_sex_male : married/widowed                  -0.076913   
personal_status_sex_male : single                            0.098989   
other_debtors_co-applicant                                   0.020268   
other_debtors_guarantor                                      0.003830   
other_debtors_none                                          -0.017249   
property_if not A121 : building society savings...          -0.045850   
property_if not A121/A122 : car or other, not i...           0.107919   
property_real estate                                        -0.226327   
property_unknown / no property                               0.198525   
other_installment_plans_bank                                 0.007769   
other_installment_plans_none                                -0.027750   
other_installment_plans_stores                               0.037686   
housing_for free                                             0.184443   
housing_own                                                 -0.047023   
housing_rent                                                -0.091729   
job_management/ self-employed/ highly qualified...           0.192996   
job_skilled employee / official      

### Drop the original variables which are converted to dummy

In [18]:
#Once converted to dummies original variable gets removed.

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [19]:

x_train,x_test,y_train,y_test = train_test_split(x_train_data_tf,y_train,test_size=0.3)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(350, 61) (150, 61) (350,) (150,)


### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [20]:

from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier(n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999)
random_forest_model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
            oob_score=False, random_state=9999, verbose=0,
            warm_start=False)

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_predicted = random_forest_model.predict(x_test)
print("confusion matrix")
print(confusion_matrix(y_test,y_predicted))
print('')
print("accuracy score")
print(accuracy_score(y_test,y_predicted))

confusion matrix
[[94 16]
 [22 18]]

accuracy score
0.7466666666666667


### Q6 Show the list of the features importance( 1 Marks)

In [22]:
feature_importance=random_forest_model.feature_importances_
feature_importance

array([0.07067738, 0.07685862, 0.03164927, 0.03349229, 0.07978359,
       0.01464417, 0.01282417, 0.01845757, 0.04678162, 0.00610796,
       0.08419911, 0.01613464, 0.01870947, 0.00807862, 0.01315689,
       0.0091695 , 0.00469775, 0.01048221, 0.01338488, 0.00858086,
       0.01432733, 0.00100516, 0.00283756, 0.01358893, 0.00260057,
       0.00098627, 0.00861775, 0.01856244, 0.00804824, 0.00618366,
       0.01319132, 0.01428717, 0.0124154 , 0.01397658, 0.01100192,
       0.00679299, 0.01340199, 0.01060645, 0.00973484, 0.01658824,
       0.00668293, 0.00692507, 0.00925736, 0.01283885, 0.0164709 ,
       0.01372788, 0.01155287, 0.01504538, 0.01651011, 0.00827616,
       0.00672363, 0.01297159, 0.00978984, 0.01164222, 0.017764  ,
       0.0032029 , 0.01082635, 0.01328176, 0.01303588, 0.00350421,
       0.00334473])

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [23]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [24]:
# Use below values
num_folds = 10
seed = 77

In [25]:
#Validate the Random Forest model build above using k fold

In [26]:
k_fold=KFold(n_splits=num_folds,random_state=seed)
scores=cross_val_score(random_forest_model,x_train,y_train,cv=k_fold)
scores

array([0.77142857, 0.8       , 0.77142857, 0.8       , 0.77142857,
       0.62857143, 0.77142857, 0.74285714, 0.68571429, 0.74285714])

In [27]:
#Calculate Mean score

In [28]:

scores.mean()

0.7485714285714286

In [29]:
# Calculate score standard deviation using std()

In [30]:

scores.std()

0.05078968238466052

# Q8 Print the confusion matrix( 1 Marks)

In [31]:

confusion_matrix(y_test,y_predicted)

array([[94, 16],
       [22, 18]], dtype=int64)

# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

In [32]:

from sklearn.metrics import recall_score,precision_score

In [33]:

print('recall {}'.format(recall_score(y_test,y_predicted)))
print('precision {}'.format(precision_score(y_test,y_predicted)))

recall 0.45
precision 0.5294117647058824


# Q10.Plot Receiver Operating Characteristic (ROC) Curves( 1 Marks)

In [34]:
#Hint: Use roc_curve

In [35]:

from sklearn.metrics import roc_curve
roc_curve(y_test,y_predicted)

(array([0.        , 0.14545455, 1.        ]),
 array([0.  , 0.45, 1.  ]),
 array([2, 1, 0], dtype=int64))

ROC curve can help you to choose a threshold that balances sensitivity and specificity in a way that makes sense for your particular context

# Q11. Calculate AUC(the percentage of the ROC plot that is underneath the curve) - optional

In [36]:
from sklearn.metrics import roc_auc_score

In [37]:

roc_auc_score(y_test,y_predicted)

0.6522727272727272

### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [38]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [39]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(x_train, y_train)
    random_forest_model.fit(X_, y_)
    y_pred = random_forest_model.predict(x_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)

In [40]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())

Accuracy Score
Avearge:  0.722
Standard deviation:  0.0351567916624939
